# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('division', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('date_closing', models.DateField()),
                ('url_detail', models.CharField(max_length=500)),
                ('url_apply', models.CharField(max_length=500)),
                ('salray_waged', models.BooleanField()),
                ('salary_amount', models.FloatField()),
            ],
        ),
    ]
