# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_auto_20160220_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url_apply',
        ),
    ]
