# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_remove_job_url_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.CharField(default='Ontario', max_length=100),
            preserve_default=False,
        ),
    ]
