# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_job_date_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='division',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
